### ISSUE TITLE
[DOCS] Supporting Upgrades from 6.x to 7.x

### ISSUE THREAD

**Issue by lcawl** [elastic/stack-docs#250]
This issue is meant to give a high level overview of all the work needed to update the documentation for users upgrading from 6.x to 7.x. 

Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/7.0/index.html):

- [ ] Update upgrade steps. See https://github.com/elastic/stack-docs/pull/242
- [ ] Verify list of "notable" breaking changes.
- [ ] Address feedback in https://github.com/elastic/stack-docs/issues/226

Elasticsearch Reference:

- [ ] Update upgrade steps in https://www.elastic.co/guide/en/elasticsearch/reference/7.0/setup-upgrade.html. See https://github.com/elastic/elasticsearch/pull/39944
- [ ] Update machine learning considerations. See https://github.com/elastic/elasticsearch/pull/40006
- [ ] Deprecate migration APIs. See https://github.com/elastic/elasticsearch/pull/40075

Kibana Guide:

- [ ]  Verify upgrade steps in https://www.elastic.co/guide/en/kibana/7.0/upgrade.html)
- [ ] Verify Upgrade Assistant screenshots and details (https://www.elastic.co/guide/en/kibana/7.0/upgrade-assistant.html)

Logstash Reference:

- [ ] Verify upgrade steps in https://www.elastic.co/guide/en/logstash/7.0/upgrading-logstash.html

Beats Platform Reference:

- [ ] Verify upgrade steps in https://www.elastic.co/guide/en/beats/libbeat/7.0/upgrading.html

APM?
