### ISSUE TITLE
Roadmap for 7.3 data frame documentation

### ISSUE THREAD

**Issue by lcawl** [elastic/stack-docs#406]
- [x] Update [conceptual overview](https://www.elastic.co/guide/en/elastic-stack-overview/master/ml-dataframes.html) to mention continuous checkpointing: https://github.com/elastic/stack-docs/pull/412
- [x] Update [data frame example](https://www.elastic.co/guide/en/elastic-stack-overview/master/ecommerce-dataframes.html) likewise: https://github.com/elastic/stack-docs/pull/410
- [x] Add sync property to [create data frame transform API](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-data-frame-transform.html): https://github.com/elastic/elasticsearch/pull/44254
- [x] Add lower-level details about how data frames work. Part one: https://github.com/lcawl/stack-docs/pull/3
- [x] [Blurb for 7.3 Kibana and Elasticsearch release highlights](https://docs.google.com/document/d/1A3WfzN2zcTl18yLtWXsp_7QdAL1UDOKwp-gkXzK6xm8/edit?usp=sharing): https://github.com/elastic/elasticsearch/pull/44907
- [x] [Limitations](https://www.elastic.co/guide/en/elastic-stack-overview/master/ml-limitations.html) See https://github.com/elastic/stack-docs/pull/407
- [x] Troubleshooting: https://github.com/elastic/stack-docs/pull/431
~- [ ] Add get data frame transform statistics resource details See https://github.com/elastic/elasticsearch/pull/44197~
- [x] Add [source and dest objects](https://www.elastic.co/guide/en/elasticsearch/reference/master/put-data-frame-transform.html) inline in API (rather than as separate pages) https://github.com/elastic/elasticsearch/pull/44504 and https://github.com/elastic/elasticsearch/pull/44509
- [x] Rename `Data frame APIs` and stack docs `Data frames` to `Data frame transforms` : https://github.com/elastic/elasticsearch/pull/44458
- [x] Describe scenarios where it makes sense to use data frames instead of aggregations: https://github.com/elastic/stack-docs/pull/435
