### ISSUE TITLE
Clients docs review roadmap # 1 - Javascript

### ISSUE THREAD

**Issue by szabosteve** [elastic/stack-docs#594]
This ticket is for keeping tack the effort of the Clients docs review process.

The first phase of the review process focuses on the [Javascript book](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/master/index.html).

- [x] Introduction https://github.com/elastic/elasticsearch-js/pull/985
- [x] Usage https://github.com/elastic/elasticsearch-js/pull/988
- [x] Client configuration https://github.com/elastic/elasticsearch-js/pull/998
- [x] API Reference https://github.com/elastic/elasticsearch-js/pull/1006
- [x] Breaking changes coming from the old client https://github.com/elastic/elasticsearch-js/pull/1012
- [x] Authentication https://github.com/elastic/elasticsearch-js/pull/1017
- [x] Observability https://github.com/elastic/elasticsearch-js/pull/1055
- [x] Creating a child client https://github.com/elastic/elasticsearch-js/pull/1057
- [x] Extend the client https://github.com/elastic/elasticsearch-js/pull/1064
- [x] TypeScript support https://github.com/elastic/elasticsearch-js/pull/1078
- [x] Examples https://github.com/elastic/elasticsearch-js/pull/1078
