### ISSUE TITLE
[7.5] Roadmap for classification documentation

### ISSUE THREAD

**Issue by szabosteve** [elastic/stack-docs#629]
- [x] Conceptual overview https://github.com/elastic/stack-docs/pull/636
- [x] Classification in reference API docs https://github.com/elastic/elasticsearch/pull/48241
- [x] Classification in resource API docs https://github.com/elastic/elasticsearch/pull/48241
- [x] Additional content for DFA evaluation conceptual doc https://github.com/elastic/stack-docs/pull/636
- [x] Additional content for DFA evaluation API doc https://github.com/elastic/elasticsearch/pull/47657
- [x] Related attributes https://github.com/elastic/docs/pull/1260
- [x] Further details (see comments below)

**Comment by szabosteve** [comment]
Best practice: https://github.com/elastic/ml-team/issues/226#issuecomment-542593692

**Comment by szabosteve** [comment]
- [ ] Sample response in PUT API docs
