### ISSUE TITLE
[7.6] Roadmap for inference documentation

### ISSUE THREAD

**Issue by szabosteve** [elastic/stack-docs#691]
- [x] Conceptual overview: https://github.com/elastic/stack-docs/pull/758
- [x] Inference in API docs: https://github.com/elastic/elasticsearch/pull/50224
- [x] Inference in pipeline processors docs: https://github.com/elastic/elasticsearch/pull/50204
- [x] Related attributes https://github.com/elastic/docs/pull/1616

**Comment by szabosteve** [comment]
Inference settings: https://github.com/elastic/elasticsearch/pull/49309
