### ISSUE TITLE
Write introductory content for the ML book

### ISSUE THREAD

**Issue by szabosteve** [elastic/stack-docs#701]
We would like to turn the [Introduction](https://www.elastic.co/guide/en/elastic-stack-overview/master/introduction.html) section into something more useful.  Ideally, it would be similar to what’s been done for [Elasticsearch](https://www.elastic.co/guide/en/kibana/master/introduction.html). That content has the warm and welcoming tone of the definitive guide, which was very popular with our users.

Possible topics for the introduction:

- [x] Overview of when you’d choose to use anomaly detection vs outlier detection vs classification etc.
- [x] Ethical considerations (how to minimize reinforcing biases in ML) https://github.com/elastic/stack-docs/pull/721
- [x] Tips for preparing your data for analysis (e.g. workflow of ingesting, preparing, transforming, analyzing, evaluating)
- [x] Performance tips (e.g. sizing ML nodes, how to work with AD, DFA, transforms at scale)
- [x] Introduction to supervised learning https://github.com/elastic/stack-docs/pull/1306
