### ISSUE TITLE
Clients docs review roadmap # 2 - PHP

### ISSUE THREAD

**Issue by szabosteve** [elastic/stack-docs#883]
This ticket is for keeping tack the effort of the Clients docs review process.

The second phase of the review process focuses on the [PHP book](https://www.elastic.co/guide/en/elasticsearch/client/php-api/master/index.html).

- [x] Overview https://github.com/elastic/elasticsearch-php/pull/999
- [x] Quickstart https://github.com/elastic/elasticsearch-php/pull/999
- [x] Installation https://github.com/elastic/elasticsearch-php/pull/1004
- [x] Configuration https://github.com/elastic/elasticsearch-php/pull/1004
- [x] Per-request configuration https://github.com/elastic/elasticsearch-php/pull/1005
- [x] Future Mode https://github.com/elastic/elasticsearch-php/pull/1005
- [x] Dealing with JSON Arrays and Objects in PHP https://github.com/elastic/elasticsearch-php/pull/1007
- [x] Index Management Operations https://github.com/elastic/elasticsearch-php/pull/1007
- [x] Indexing Documents https://github.com/elastic/elasticsearch-php/pull/1010
- [x] Getting Documents https://github.com/elastic/elasticsearch-php/pull/1010
- [x] Updating Documents https://github.com/elastic/elasticsearch-php/pull/1010
- [x] Deleting documents https://github.com/elastic/elasticsearch-php/pull/1010
- [x] Search Operations https://github.com/elastic/elasticsearch-php/pull/1010
- [x] Namespaces https://github.com/elastic/elasticsearch-php/pull/1011
- [x] Security https://github.com/elastic/elasticsearch-php/pull/1011
- [x] Connection Pool https://github.com/elastic/elasticsearch-php/pull/1018
- [x] Selectors https://github.com/elastic/elasticsearch-php/pull/1018
- [x] Serializers https://github.com/elastic/elasticsearch-php/pull/1023
- [x] PHP Version Requirement https://github.com/elastic/elasticsearch-php/pull/1023
- [x] Breaking changes from 6.x https://github.com/elastic/elasticsearch-php/pull/1025
- [x] Community DSLs https://github.com/elastic/elasticsearch-php/pull/1025
- [x] Community Integrations https://github.com/elastic/elasticsearch-php/pull/1025
- [x] Experimental and beta APIs https://github.com/elastic/elasticsearch-php/pull/1027

Issue of the first phase: https://github.com/elastic/stack-docs/issues/594
